services:
    jhg_status_page.response_time.status_listener:
        class: Jhg\StatusPageBundle\EventListener\ResponseTimeListener
        arguments: ["@jhg_status_page.status_stack"]
        tags:
            - { name: kernel.event_subscriber }