services:
    jhg_status_page.status_stack:
        class: Jhg\StatusPageBundle\Status\StatusStack
        arguments: [ '' ]

    jhg_status_page.status_flush.event_listener:
        class: Jhg\StatusPageBundle\EventListener\StatusFlushListener
        arguments: ["@jhg_status_page.status_stack"]
        tags:
            - { name: kernel.event_subscriber }

    jhg_status_page.twig_extension:
        class: Jhg\StatusPageBundle\Twig\StatusPageExtension
        tags:
            - { name: twig.extension }