services:
    jhg_status_page.status_stack:
        class: Jhg\StatusPageBundle\Event\EventManager
        arguments: [ "@snc_redis.status" ]

    jhg_status_page.record.event_listener:
        class: Jhg\StatusPageBundle\EventListener\StatusRecordListener
        arguments: ["@jhg_status_page.status_stack"]
        tags:
            - { name: kernel.event_subscriber }

    jhg_status_page.twig_extension:
        class: Jhg\StatusPageBundle\Twig\StatusPageExtension
        tags:
            - { name: twig.extension }