services:
    jhg_status_page.watchdogs_processor:
        class: Jhg\StatusPageBundle\WatchDogs\WatchDogProcessor
        arguments: [ '@jhg_status_page.status_stack', '%jhg_status_page.watchdogs%', '', '@security.expression_language']

    jhg_status_page.watchdogs_reader:
        class: Jhg\StatusPageBundle\WatchDogs\WatchDogReader
        arguments: [ '%jhg_status_page.watchdogs%', '']

    jhg_status_page.watchdog.twig_extension:
        class: Jhg\StatusPageBundle\Twig\WatchDogExtension
        arguments: ['@jhg_status_page.watchdogs_reader']
        tags:
            - { name: twig.extension }